"""
client.py

Small async client for the subset of Spotify's Web API used by the app.
"""

# ==================================================
# Imports and Configuration
# ==================================================

from __future__ import annotations

from typing import Any

import httpx

from ..core.models import Track

SPOTIFY_API_BASE = "https://api.spotify.com/v1"

# ==================================================
# Exception Classes
# ==================================================


class SpotifyAPIError(RuntimeError):
    """Raised when Spotify returns a non-successful API response."""

    def __init__(self, status_code: int, message: str) -> None:
        super().__init__(f"Spotify API error {status_code}: {message}")
        self.status_code = status_code
        self.message = message


# ==================================================
# Client Class
# ==================================================


class SpotifyClient:
    """Async client for the subset of Spotify's Web API used by the app."""

    def __init__(self, access_token: str, timeout: float = 15.0) -> None:
        self.access_token = access_token
        self.timeout = timeout

    @property
    def headers(self) -> dict[str, str]:
        return {
            "Authorization": f"Bearer {self.access_token}",
            "Content-Type": "application/json",
        }

    async def _request(
        self,
        method: str,
        path: str,
        *,
        params: dict[str, Any] | None = None,
        json: dict[str, Any] | None = None,
    ) -> dict[str, Any]:
        """Make an async request to the Spotify Web API and return the JSON response."""
        async with httpx.AsyncClient(timeout=self.timeout) as client:
            response = await client.request(
                method,
                f"{SPOTIFY_API_BASE}{path}",
                headers=self.headers,
                params=params,
                json=json,
            )

        if response.status_code >= 400:
            try:
                detail = response.json()
            except ValueError:
                detail = response.text
            raise SpotifyAPIError(response.status_code, str(detail))

        if response.status_code == 204:
            return {}

        return response.json()

    async def get_current_user(self) -> dict[str, Any]:
        """Return the authenticated Spotify user's public profile."""

        return await self._request("GET", "/me")

    async def search_tracks(
        self,
        query: str,
        *,
        market: str = "GB",
        limit: int = 10,
        offset: int = 0,
    ) -> list[Track]:
        """
        Search Spotify for tracks.

        Spotify currently caps search ``limit`` at 10, so calls should be paged
        when they need a larger candidate pool.
        """

        limit = min(max(limit, 1), 10)

        data = await self._request(
            "GET",
            "/search",
            params={
                "q": query,
                "type": "track",
                "market": market,
                "limit": limit,
                "offset": offset,
            },
        )

        tracks = data.get("tracks", {}).get("items", [])
        return [self._track_from_spotify(item) for item in tracks if item]

    async def get_track(self, track_id: str, *, market: str = "GB") -> Track:
        """Get a track by its Spotify ID."""
        data = await self._request(
            "GET",
            f"/tracks/{track_id}",
            params={"market": market},
        )
        return self._track_from_spotify(data)

    async def create_playlist(
        self,
        name: str,
        *,
        description: str = "Generated by Running Playlist Generator",
        public: bool = False,
    ) -> dict[str, Any]:
        """Create an empty playlist for the current user."""

        return await self._request(
            "POST",
            "/me/playlists",
            json={
                "name": name,
                "description": description,
                "public": public,
                "collaborative": False,
            },
        )

    async def add_items_to_playlist(
        self,
        playlist_id: str,
        track_ids: list[str],
    ) -> None:
        """Add tracks to a playlist in chunks of 100."""

        for start in range(0, len(track_ids), 100):
            chunk = track_ids[start : start + 100]
            await self._request(
                "POST",
                f"/playlists/{playlist_id}/items",
                json={
                    "uris": [f"spotify:track:{track_id}" for track_id in chunk],
                },
            )

    @staticmethod
    def _track_from_spotify(item: dict[str, Any]) -> Track:
        artists = item.get("artists") or []
        artist_name = ", ".join(
            artist.get("name", "Unknown Artist") for artist in artists
        )

        external_ids = item.get("external_ids") or {}
        external_urls = item.get("external_urls") or {}

        return Track(
            spotify_id=item["id"],
            name=item["name"],
            artist=artist_name or "Unknown Artist",
            duration_seconds=max(1, round(item.get("duration_ms", 0) / 1000)),
            isrc=external_ids.get("isrc"),
            explicit=item.get("explicit"),
            popularity=item.get("popularity"),
            spotify_uri=item.get("uri"),
            spotify_url=external_urls.get("spotify"),
        )
